# active spring boot profile
spring:
  profiles:
    active: dev

---
# common - spring configuration
spring:

  # devtools - live reload
  devtools:
    livereload:
      enabled: true

  # mvc
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
  jpa:
    hibernate:
      ddl-auto: validate # 
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true


---

# dev profile - spring boot configuration

spring:
  config:
    activate:
      on-profile: dev


  # datasource
  datasource:
      username: root
      password: 1234
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/itfo?characterEncoding=utf8

---

##mybatis
mybatis:
  config-location: classpath:mybatis/configuration.xml